#!/bin/sh

cd `dirname $0`
. ./Configuration

# Compile Python Programs
echo "Compiling python programs..."
python -c 'import compileall; compileall.compile_dir(".")'

#
# Create the runtime files if they don't exist
#
if [ ! -d ${DATALOADSOUTPUT}/mgi/vocload/archiveMouseCyc ]
then
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/archiveMouseCyc
fi
if [ ! -d ${DATALOADSOUTPUT}/mgi/vocload/runTimeMouseCyc ]
then
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/runTimeMouseCyc
fi

if [ ! -d ${DATALOADSOUTPUT}/mgi/vocload/OMIM ]
then
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/OMIM
fi

if [ ! -d ${DATALOADSOUTPUT}/mgi/vocload/archiveMA ]
then
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/archiveMA
fi
if [ ! -d ${DATALOADSOUTPUT}/mgi/vocload/runTimeMA ]
then
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/runTimeMA
fi

if [ ! -d ${DATALOADSOUTPUT}/mgi/vocload/archiveMP ]
then
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/archiveMP
fi
if [ ! -d ${DATALOADSOUTPUT}/mgi/vocload/runTimeMP ]
then
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/runTimeMP
fi

if [ ! -d ${DATALOADSOUTPUT}/mgi/vocload/archiveGO ]
then
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/archiveGO
fi
if [ ! -d ${DATALOADSOUTPUT}/mgi/vocload/runTimeGO ]
then
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/runTimeGO
fi

if [ ! -d ${DATALOADSOUTPUT}/mgi/vocload/archiveRV ]
then
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/archiveRV
fi
if [ ! -d ${DATALOADSOUTPUT}/mgi/vocload/runTimeRV ]
then
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/runTimeRV
fi

if [ ! -d ${DATALOADSOUTPUT}/mgi/vocload/archiveCL ]
then
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/archiveCL
fi
if [ ! -d ${DATALOADSOUTPUT}/mgi/vocload/runTimeCL ]
then
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/runTimeCL
fi

if [ ! -d ${DATALOADSOUTPUT}/mgi/vocload/archiveBiotype ]
then
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/archiveBiotype
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/archiveBiotype/ensembl
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/archiveBiotype/ncbi
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/archiveBiotype/vega
fi
if [ ! -d ${DATALOADSOUTPUT}/mgi/vocload/runTimeBiotype ]
then
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/runTimeBiotype
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/runTimeBiotype/ensembl
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/runTimeBiotype/ncbi
    mkdir -p ${DATALOADSOUTPUT}/mgi/vocload/runTimeBiotype/vega
fi

# Set mode
echo "Setting modes..."
chmod 775 *

