#!/usr/local/bin/python

#
# Program: OMIMtermreport.py
#
# Original Author: Lori Corbani
#
# Purpose:
#
#	To generate report 1 of OMIM.txt term vs. MGI OMIM term
#	where the:
#		OMIM.tab id = MGI OMIM id
#		OMIM.tab term != MGI OMIM term
#
#	For example:
#		OMIM.tab id = MGI OMIM id = 244400
#		OMIM.tab term = "Ciliary Dyskinesia, Primary, 1"
#		MGI OMIM term = "Kartagener Syndrome"
#
#	Report output 1:
#
#		MGI OMIM ID
#		MGI OMIM term
#		OMIM.tab term
#
#	TR9461
#	To generate report 2 of merged OMIM terms
#	where the:
#		OMIM.tab id = MGI OMIM id
#		OMIM.tab secondary exists
#		OMIM.tab term
#		MGI OMIM term
#
#	Report output 2:
#
#		MGI OMIM ID
#		OMIM.tab secondary ID (column 7)
#		MGI OMIM secondary ID
#
# Inputs:
#
#	/data/loads/mgi/vocload/OMIM/OMIM.tab
#
#	as is generated by OMIM.py 
#
# Outputs:
#
#	Report: OMIMtermcheck.rpt
#
# History
#
# 12/23/2015	lec
#	- TR11956/added report2/moved report2 to report3
#
# 08/06/2009	lec
#	- TR9461; add report of secondary OMIM terms
#

import sys 
import os
import string
import db
import reportlib

CRT = reportlib.CRT
SPACE = reportlib.SPACE
TAB = reportlib.TAB
PAGE = reportlib.PAGE

def report1():

    fp.write('''A report of new OMIM.tab term vs. MGI OMIM term where the:
           OMIM.tab id = MGI OMIM id
           OMIM.tab term != MGI OMIM term
           ''')

    fp.write(CRT)
    fp.write(string.ljust('MGI OMIM ID', 15) + TAB)
    fp.write(string.ljust('MGI OMIM term', 65) + TAB)
    fp.write(string.ljust('OMIM.tab term', 65) + CRT*2)
    #fp.write('MGI ID of the Genotype annotations' + CRT*2)

    for t in mgiTerms:
        if omimTerms.has_key(t):
	    mTerm = mgiTerms[t]
	    oTerm = omimTerms[t]

	    # only print if the terms are not equal

	    if mTerm != oTerm:
	        fp.write(string.ljust(t, 15) + TAB)
	        fp.write(string.ljust(mgiTerms[t], 65) + TAB)
	        fp.write(string.ljust(omimTerms[t], 65) + CRT)

    fp.write(CRT*2)

def report2():

    fp.write('''A report of new OMIM.tab term vs. MGI OMIM term where the:
           OMIM.tab id = MGI OMIM id
           OMIM.tab term != MGI OMIM term
           ''')

    fp.write(CRT)
    fp.write(string.ljust('MGI OMIM ID', 15) + TAB)
    fp.write(string.ljust('MGI OMIM term', 65) + TAB)
    fp.write(string.ljust('OMIM.tab term', 65) + CRT*2)

    for t in mgiTerms:
        if omimTerms.has_key(t):
	    mTerm = mgiTerms[t]
	    oTerm = omimTerms[t]

	    # only print if the terms are not equal

	    if mTerm != oTerm:
	        fp.write(string.ljust(t, 15) + TAB)
	        fp.write(string.ljust(mgiTerms[t], 65) + TAB)
	        fp.write(string.ljust(omimTerms[t], 65) + CRT)

    fp.write(CRT*2)

def report3():

    fp.write('''A report of secondary OMIM.tab ids vs. MGI OMIM secondary ids where the:
           OMIM.tab id = MGI OMIM id
	   OMIM.tab secondary id != MGI OMIM secondary id
           ''')

    fp.write(CRT)
    fp.write(string.ljust('MGI OMIM ID', 15) + TAB)
    fp.write(string.ljust('MGI OMIM secondary ID', 25) + TAB)
    fp.write(string.ljust('OMIM secondary ID', 25) + CRT*2)

    # for each omim secondary that exists in mgi as a primary...
    for t in mgiSecondarys:

	secondaryExists = 0

        if omimSecondarys.has_key(t):

	    mSecondary = mgiSecondarys[t]

	    for oSecondary in omimSecondarys[t]:
	        if mSecondary == oSecondary:
		    secondaryExists = 1

	    # only print if the secondaries are not equal

	    if secondaryExists == 0:
	        fp.write(string.ljust(t, 15) + TAB)
	        fp.write(string.ljust(mgiSecondarys[t], 25) + TAB)
	        fp.write(string.ljust(string.join(omimSecondarys[t],'|'), 25) + CRT)

    fp.write(CRT*2)

def init():

    global omimTerms, omimSecondarys, mgiTerms, mgiSecondarys

    # grab the new OMIM terms
    for line in inFile.readlines():
        tokens = string.split(line[:-1], '\t')
        term = tokens[0]
        id = tokens[1]
	secondary = tokens[7]
        omimTerms[id] = term

	if len(secondary) > 0:
	    tokens = string.split(secondary, '|')
	    omimSecondarys[id] = []
	    for t in tokens:
		omimSecondarys[id].append(t)

    inFile.close()

    # grab the existing OMIM terms in MGI
    results = db.sql('''select a.accID, t.term
        from VOC_Term t, ACC_Accession a
        where t._Vocab_key = 44
        and t._Term_key = a._Object_key 
        and a._MGIType_key = 13 
        and a.preferred = 1
        order by t.term, a.accID
        ''', 'auto')

    for r in results:
        term = r['term']
        id = r['accID']
        mgiTerms[id] = term

    # grab the existing OMIM secondary terms in MGI
    results = db.sql('''select distinct a.accID, s.accID as secondary
        from VOC_Term t, ACC_Accession a, ACC_Accession s
        where t._Vocab_key = 44
        and t._Term_key = a._Object_key 
        and a._MGIType_key = 13 
        and a.preferred = 1
        and t._Term_key = s._Object_key 
        and s._MGIType_key = 13 
        and s.preferred = 0
        order by s.accID, a.accID
        ''', 'auto')

    for r in results:
        id = r['accID']
	secondary = r['secondary']
        mgiSecondarys[id] = secondary

#
# Main
#

fp = reportlib.init(sys.argv[0], printHeading = 0, outputdir = os.environ['RUNTIME_DIR'],
	fileExt = '.' + os.environ['DATE'] + '.rpt')
os.system('rm -rf ${RUNTIME_DIR}/OMIMtermcheck.current.rpt')
os.system('ln -s ${RUNTIME_DIR}/OMIMtermcheck.${DATE}.rpt ${RUNTIME_DIR}/OMIMtermcheck.current.rpt')

# this is the data file generated by OMIM.py/see OMIM.config
inFile = open(os.environ['DATA_FILE'], 'r')

omimTerms = {}
omimSecondarys = {}
mgiTerms = {}
mgiSecondarys = {}

init()
report1()
report2()
report3()
reportlib.finish_nonps(fp)	# non-postscript file

