#!/bin/sh
#
#  runEmapQC
###########################################################################
#
# A copy of this script is intended to reside in /usr/local/bin on all
# servers to make it available in the common PATH.
#
# Its allows someone to run the EMAPA/EMAPS load sanity checks without having
# to provide the full path to where the wrapper script is installed.
#
###########################################################################

usage ()
{
    echo "Usage: runEMAPQC input_file"
    echo "       where"
    echo "           input_file = path to the EMAPA.obo file"
    exit 1
}

#
#  If the MGICONFIG environment variable does not have a local override,
#  use the default "live" settings.
#
if [ "${MGICONFIG}" = "" ]
then
    MGICONFIG=/usr/local/mgi/live/mgiconfig
    export MGICONFIG
fi

. ${MGICONFIG}/master.config.sh

#
# The emapload product is not installed on all servers, so make sure
# it exists on this one.
#
if [ ! -d ${VOCLOAD}/emap ]
then
    echo "The emapload software does not exist on this server"; exit 1
fi

#
# Make sure an input file was passed as an argument to the script.
#
if [ $# -eq 1 ]
then
    if [ ! -r $1 ]
    then
        echo "Input file does not exist: $1"; exit 1
    fi
else
    usage
fi

#
# Invoke the sanity check wrapper script with the argument
# passed to this script. This actually invokes the load script in 
# QC mode
#
${VOCLOAD}/emap/emapQC.sh $1

